:sparkles: feat : 이벤트 상세보기 및 MY EVENT 등록#99
innovationacademy-kr/our42vent pull request #101
Opened 2022-01-25 08:24 UTC by sehhong3317

## 개요
- 캘린더내 띠지 선택시, 해당 이벤트의 상세보기 창 생성
- 상세보기 창내, 알림 설정 옵션 제공
- 해당 이벤트 내 관심 이벤트로 등록

## 작업 사항
- 띠지 선택시, get /event/eventId를 통해 해당 띠지의 이벤트 상세 정보를 불러줌.
- generateMonth(), resizeHandler()안에서  날짜, 공휴일 및 띠지 rendering 완료후, 각 띠지에 대한 click 이벤트 리스너 설정함.
- '내 이벤트로 등록' 클릭시, post /event/myevent/eventId로 my_event 테이블에 관심이벤트 추가함.
- 띠지의 이벤트 상세 정보를 보여주는 함수(clickEventDetails())가 css적용을 하다보니, 많은 부분이 수정될 필요가 있습니다.
- 개선할 부분 말씀해주시면 반영하도록 하겠습니다.

## 스크린샷 (optional)
<img width="1434" alt="스크린샷 2022-01-25 오후 5 12 09" src="https://user-images.githubusercontent.com/84187808/150937409-236d3b0a-a387-4326-85f3-5590e85e2ade.png">

2022-01-25 08:58 UTC, yongjulejule requested changes
고생하셨습니다~~ 수정사항 반영 부탁드려욤

2022-01-25 08:58 UTC, yongjulejule commented on controllers/insertMyEventController.js
> +
바로 밑에 selectEventController 함수처럼 에러 핸들링 부탁드려요~~

2022-01-25 08:58 UTC, yongjulejule commented on public/stylesheets/components/event_details.css
> +  overflow: auto;
-ms*, -webkit*...등등의 prefix는 제외하고 정렬해주세여

2022-01-25 08:58 UTC, yongjulejule commented on public/javascripts/eventDetail/clickEventDetails.js
> +import setBeginAt from './utils/setBeginAt.js';
알파벳순 맞춰주세여

2022-01-25 08:58 UTC, yongjulejule commented on public/javascripts/generateCalendars/month/generateMonth.js
> +import clickEventDetails from '../../eventDetail/clickEventDetails.js';
3번째줄 <-> 4번째줄 순서 바꿔주세요~~

2022-01-25 08:58 UTC, yongjulejule commented on public/javascripts/generateCalendars/month/resizeHandler.js
> +import clickEventDetails from '../../eventDetail/clickEventDetails.js';
여기도 알파벳순 맞춰주세여~~

2022-01-25 08:58 UTC, yongjulejule commented on public/stylesheets/components/event_details.css
> +
이 아이 추가해주세여~~
```
.details-topic-content::-webkit-scrollbar {
  display: none;
}
```

2022-01-25 08:58 UTC, yongjulejule commented on public/javascripts/eventDetail/clickEventDetails.js
> +      headers: { 'Content-Type': 'application/json' },
여기 headers 없어도 된다네여

2022-01-25 09:26 UTC, 42ghan requested changes
수고많으셨습니다! 몇가지만 수정 부탁드려요~

2022-01-25 09:26 UTC, 42ghan commented on public/javascripts/eventDetail/utils/setCategoryName.js
> +      finalCategory = '멘토특강';
- '멘토특강' -> '특강'으로 수정 부탁드립니다.

2022-01-25 09:26 UTC, 42ghan commented on public/javascripts/eventDetail/utils/setBeginAt.js
> +  const beginAtInStr = `${year}년 ${month}월 ${date}일 (${day}) ${hour}:${modifiedMinute}`;
- `Date` 객체로 여러번 method 호출 하는 것보다 string split 해서 하는게 더 효율적일 것 같습니다.

2022-01-25 09:26 UTC, 42ghan commented on controllers/selectEventController.js
> +  }
- catch 할 때 적절한 로그 찍어주시면 좋을 것 같아요.

2022-01-25 09:26 UTC, 42ghan commented on public/javascripts/eventDetail/clickEventDetails.js
> +    return err;
- 호출하는 함수에서 잡아주니 없어도 되는 catch 같습니다. 지워주세요.

2022-01-25 09:26 UTC, 42ghan commented on public/javascripts/eventDetail/clickEventDetails.js
> +    console.log(err.message);
- 추후에 에러 페이지 표시 해야하니 TODO 주석으로 하이라이트 해주세요.

2022-01-25 09:26 UTC, 42ghan commented on public/javascripts/eventDetail/clickEventDetails.js
> +      detailElement.id = event.classList[0];
- 복수행 주석은 `/** */` 로 감싸주세요.

2022-01-25 11:07 UTC, jis-kim requested changes
빅기능 수고하셨습니다! 조금만 수정해주세요 짱짱세희님

2022-01-25 11:07 UTC, jis-kim commented on public/javascripts/eventDetail/utils/setNotification.js
> +  switch (notificationOption) {
위에서 말씀 드렸지만 이 부분을 컨트롤러에서 number 변환으로 변경해주세요~!

2022-01-26 04:01 UTC, yongjulejule commented on public/javascripts/eventDetail/clickEventDetails.js
> +  return res.data;
에러 핸들링이 필요합니다 하하

2022-01-26 04:04 UTC, yongjulejule commented on public/javascripts/eventDetail/clickEventDetails.js
> +  return res.data;
하하 필요없네요 하하하

2022-01-26 04:07 UTC, 42ghan approved these changes
수고하셨습니다! @yongjulejule @jis-kim  수정 필요한 사항 comment 로 달아주시고 approve 해주시면 제가 merge 하면서 반영하겠습니다~

2022-01-26 04:07 UTC, 42ghan commented on public/javascripts/eventDetail/clickEventDetails.js
> +  return res.data;
제가 하겠습니다! approve  ㄱㄱ

2022-01-26 04:07 UTC, 42ghan commented on public/javascripts/generateCalendars/month/generateMonth.js
> +import clickEventDetails from '../../eventDetail/clickEventDetails.js';
제가 바꿀게요

2022-01-26 04:07 UTC, 42ghan commented on public/javascripts/generateCalendars/month/resizeHandler.js
> +import clickEventDetails from '../../eventDetail/clickEventDetails.js';
여기도 제가 할게요~

2022-01-26 04:09 UTC, yongjulejule approved these changes
고생하셨읍니다~~ 굿굿

2022-01-26 05:08 UTC, jis-kim approved these changes
확인했습니다 수고하셨습니다~!

2022-01-26 05:08 UTC, merged