:sparkles: 인트라 이벤트 업데이트
innovationacademy-kr/our42vent pull request #102
Opened 2022-01-25 09:24 UTC by jis-kim

## 개요
- 10분마다 db의 가장 최신 데이터를 가져와 그 이후의 이벤트를 업데이트
## 작업 사항
- db의 가장 최신 데이터를 가져와 그 이후의 이벤트를 업데이트
- init과 update 모두 가능하게 getFtAccessToken.js 모듈화
- cron으로 실행 가능하도록 env 경로 재설정
## 변경 사항
- env 경로설정을 해준다면 기존 `getEvents.js`도 아무 경로에서 실행할 수 있습니다.
- 에러 처리부분을 상황에 맞게 변경하였습니다.
## 주의 사항
- 실행 전 `getFtAccessToken.js`의 env 경로 설정 부분을 환경에 맞게 세팅 해주세요.
## 실행 방법
- `crontab -e`로 crontab 설정파일 실행
- crontab 설정파일에 해당 스크립트 입력
`*/10 * * * * [node 경로] [프로젝트경로]/db/getIntraEvents/getUpdatedEvents.js >> [로그파일] 2>&1`

close #98

2022-01-25 11:02 UTC, jis-kim commented on db/getIntraEvents/getFtAccessToken.js
> +dotenv.config({ path: 'project경로/.env' });
이 부분을 환경에 맞게 세팅해주세요!

2022-01-25 11:15 UTC, yongjulejule commented on db/getIntraEvents/getUpdatedEvents.js
> +    if (examList.length === 0) {
뭔가 eventList.length 가 와야 할 것 같이 생겼는데 아닌가여??

2022-01-25 11:16 UTC, jis-kim commented on db/getIntraEvents/getUpdatedEvents.js
> +    if (examList.length === 0) {
어 맞네요..!! 수정하겠습니다

2022-01-25 11:18 UTC, yongjulejule requested changes
몇 개 수정 부탁드립니다~~

2022-01-25 11:18 UTC, yongjulejule commented on db/getIntraEvents/getUpdatedEvents.js
> +    'select modifiedAt FROM event WHERE modifiedAt=(SELECT Max(modifiedAt) FROM event ' +
select 대문자로 부탁드립니다ㅎㅎ

2022-01-25 11:21 UTC, 42ghan requested changes
- MySQL 마스터 지스킴 멋지네요. 수고하셨습니다 👏 👏 👏 👏 ... 조금만 수정해주세요 : ]

2022-01-25 11:21 UTC, 42ghan commented on db/getIntraEvents/getEvents.js
>  import redisClient from '../../config/createRedisClient.js';
- 순서 바꿔주세요.

2022-01-25 11:21 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
> +import redisClient from '../../config/createRedisClient.js';
- 여기도 순서...

2022-01-25 11:21 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
> +    if (!token) throw new Error('token is not exist');
- 'is not' -> 'does not'

2022-01-25 11:21 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
> +    if (!token) throw new Error('token is not exist');
- 여기도 does not

2022-01-25 11:21 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
> +  if (eventList == null) return;
- `==` -> `===`

2022-01-25 11:21 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
> +    if (examList.length === 0) {
- `!examList.length` 로 바꿔주세요.

2022-01-25 11:21 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
> +updateEventData();
- 개행 please

2022-01-25 11:41 UTC, jis-kim commented on db/getIntraEvents/getUpdatedEvents.js
> +updateEventData();
thx 지한린터~ 수정했습니다

2022-01-25 11:42 UTC, yongjulejule approved these changes
굳굳~~~ 고생하셨읍니다

2022-01-25 11:47 UTC, 42ghan approved these changes
수고하셨어요!

2022-01-26 03:01 UTC, sehhong3317 approved these changes

2022-01-26 03:01 UTC, merged