:sparkles: 등록 취소 기능 구현 & 이벤트 생성, 상세정보 팝업 ui 개선
innovationacademy-kr/our42vent pull request #126
Opened 2022-01-29 09:37 UTC by 42ghan

## 개요
- 이벤트 등록 취소 기능 구현
- 과거 이벤트는 취소는 가능 등록은 불가
- 이벤트 생성 & 상세정보 팝업 ui 개선
## 변경점
- 이벤트 생성 폼 팝업 & 상세정보 팝업 내부 항목별 scroll을 팝업 scroll 로 대체
- 여백 수정
## 스크린샷
https://user-images.githubusercontent.com/83805691/151655984-3fda0423-67bc-45ac-82e4-b4f1559ec5bc.mov

2022-01-29 11:00 UTC, yongjulejule commented on public/javascripts/eventDetail/clickEventDetails.js
> +import setRange from './utils/setRange.js';
순서가 안맞아졌어요,,,

2022-01-29 11:41 UTC, yongjulejule requested changes
몇 가지만 고쳐주세요~~

2022-01-29 11:41 UTC, yongjulejule commented on routes/event.js
> +  router.delete('/myevent/:eventId', unsubscribeController);
어... 위에는 이벤트를 구독하는데... 밑에선... 뭘 취소하는지... 모르겠어요... 어렵다....

2022-01-29 13:42 UTC, yongjulejule approved these changes
고생하셨습니다~~~~

2022-01-30 04:02 UTC, 42ghan commented
이벤트 등록 취소 시 새로고침을 해야만 달력에 반영되길래 수정해줬습니다.

2022-01-30 04:25 UTC, sehhong3317 commented on public/javascripts/eventDetail/utils/setRange.js
> +  const beginModifiedMinute = beginMinute > 9 > 1 ? beginMinute : `0${beginMinute}`;
beginMinute > 9 > 1 ? 부분 오타인것 같습니다

2022-01-30 04:25 UTC, sehhong3317 approved these changes
수고하셨습니다!

2022-01-30 08:21 UTC, yongjulejule approved these changes
굿굿 섬세지한

2022-01-30 10:58 UTC, jis-kim approved these changes
수고하셨습니다~~~ ^__^

2022-01-30 10:58 UTC, merged