:sparkles: feat : 서버에서 이벤트 폼 사용자 input 유효성 검증
innovationacademy-kr/our42vent pull request #141
Opened 2022-01-31 08:32 UTC by sehhong3317

## 개요
- 이벤트 폼 input의 테두리 색을 통한 유효성 시각화
- 이벤트 폼의 시작시간, 종료시간 유효성 검증
- 서버사이드 이벤트 폼 input 유효성 검증

## 작업 사항
1. 유효성 검사
- 이벤트를 새로 생성하거나 편집할때, input의 테두리 색 변경을 통해 유효성을 시각화했습니다. 
- 이벤트 등록(axios post)전, 이벤트 폼의 모든 input이 유효한지 검증했습니다. ​
- 이벤트 폼의 시작/종료 시간의 범위를 추가로 제한했습니다. (1970년~4242년)
- event 테이블에 insert이나 update전에 input이 유효한지 추가로 검증하였습니다.

2. 추가사항
- 카테고리에 '카테고리 설정' option을 default로 추가했습니다.

2022-01-31 09:10 UTC, 42ghan requested changes
몇가지 수정 부탁드립니다! 수고하셨습니다!

2022-01-31 09:10 UTC, 42ghan commented on public/javascripts/eventForm/utils/colorizeBorder.js
> +  else element.style.border = '2px solid red';
- 삼항연산자 사용해주세요.

2022-01-31 09:10 UTC, 42ghan commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +  const endat = document.getElementById('event-endat');
- 변수 명 camelcase 로 (beginAt, endAt)으로 수정부탁드립니다.

2022-01-31 09:10 UTC, 42ghan commented on public/javascripts/eventForm/utils/addStrEventListener.js
> +function countByteAndcolorizeBorder(element, maxByte, isRequired, isTextarea) {
- 함수명 'colorizeTextBorder' 로 수정해주세요.

2022-01-31 09:10 UTC, 42ghan commented on public/javascripts/eventForm/utils/addStrEventListener.js
> +export default function addStrEventListener(inputId, maxByte, isRequired, isTextarea) {
- 함수명 & 변수명 'addTextEventListener' 로 바꿔주세요.

2022-01-31 09:20 UTC, sehhong3317 commented on lib/validateBeforeInsertOrEdit.js
> +export default function validateBeforeInsertOrEdit(event) {
validateEventData()로 바꾸겠습니다!

2022-01-31 14:31 UTC, yongjulejule requested changes
고생하셨습니다~~~~ 몇 가지만 수정 부탁드려요~~!

2022-01-31 14:36 UTC, 42ghan requested changes
수고 많으셨습니다! 한번만 더 수정 부탁드립니다 ㅎㅎ
pr 머지 된 후에 시간 되실 때 다른 브라우저들에서도 한번씩 테스트 부탁드립니다.

2022-01-31 14:36 UTC, 42ghan commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +  }
- {} 없애주세요

2022-01-31 14:36 UTC, 42ghan commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +  }
여기도 없애주세요

2022-01-31 14:36 UTC, 42ghan commented on public/javascripts/utils/eventForm/countByte.js
> +   */
- 복수행 주석은 아래와 같은 포맷으로 작성해주세요.
<img width="654" alt="Screen Shot 2022-01-31 at 11 33 54 PM" src="https://user-images.githubusercontent.com/83805691/151812664-6fb2d6cf-d1f0-4041-9f59-a6ad291c8c2f.png">

2022-02-01 02:15 UTC, sehhong3317 commented on public/javascripts/eventForm/addListenersForBorderColor.js
> +  // addTextEventListener(inputId, maxByte, isRequired, isTextarea)
이 함수 매개변수가 너무 많아서, 해당 값이 어느 매개변수의 값인지 모르실까봐 써놨습니다! 
지울게요!!;)

2022-02-01 03:39 UTC, 42ghan approved these changes
감사합니다 세희님~~

2022-02-01 04:52 UTC, jis-kim requested changes
수고하셨습니다. 코멘트 참고해주세요. 감사합니다!

2022-02-01 05:05 UTC, jis-kim requested changes

2022-02-01 05:05 UTC, jis-kim commented on public/javascripts/eventForm/addListenersForBorderColor.js
> +  addTextEventListener('event-title', 224, true, false);
true/false를 인간이 판단해서 매개변수로 넘기면 호출부분만 봤을 때 매개변수의 의미도 알 수 없고 나중에 재사용하기도 힘들기 때문에 boolean 값을 넘기기보단 `'event-title'` 같은 값을 이용하여 함수 안에서 다른 로직을 적용하거나 다른 함수를 호출하는 식으로 변경하는 것이 좋을 것 같습니다.

2022-02-01 05:05 UTC, jis-kim commented on lib/validateEventData.js
> +  isValidStr(title, 'Title', true, 224);
[함수명에 is가 붙으면](https://softwareengineering.stackexchange.com/questions/384450/is-there-a-term-for-functions-starting-with-the-is-prefix) 보통 return값이 boolean인 함수이기 때문에 함수명을 `validateStr` 이나 `checkValidStr`등의 이름으로 변경하는 게 좋을 듯 합니다.

2022-02-01 05:14 UTC, 42ghan commented on public/javascripts/eventForm/addListenersForBorderColor.js
> +  addTextEventListener('event-title', 224, true, false);
예리한 지적이네요! 함수 정의할 때 세번째 인자를 `inputType` 이라고 부르고, 함수 호출할 때 `{ isRequired : boolean, isTextArea : boolean }` 이런식으로 세번째 인자 넘겨줘서 객체 안의 property 들로 함수 내부에서 조건 점검하면 좀 더 가독성 높은 코드가 될 것 같네요.

2022-02-02 08:36 UTC, 42ghan requested changes
한번에 말씀 못드려서 죄송합니다... 한번만 더 수정부탁드립니다!

2022-02-02 08:36 UTC, 42ghan commented on lib/validateEventData.js
> +// }
주석 지워주세요

2022-02-02 08:36 UTC, 42ghan commented on lib/validateEventData.js
> +  }
{} 없애주세요

2022-02-02 08:36 UTC, 42ghan commented on public/javascripts/eventForm/utils/addCategoryEventListener.js
> +  });
{} 없애고 한 줄로 만들죠

2022-02-02 08:36 UTC, 42ghan commented on public/javascripts/eventForm/utils/addTextEventListener.js
> +  else element.style.border = '2px solid red';
삼항연산자로 바꿔주세요

2022-02-02 08:36 UTC, 42ghan commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +  });
여기도 한 줄로 바꿔버리죠

2022-02-02 08:56 UTC, 42ghan submitted a review, later dismissed
수고하셨습니다!

2022-02-02 09:12 UTC, yongjulejule requested changes
고생하셨습니다,,, 수정 부탁드립니다~~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +  return false;
return timeObj >= min && timeObj <= max 로 바꿔주세염

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addCategoryEventListener.js
> +    }, 2000);
한줄로 만들어 주세여~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addCategoryEventListener.js
> +      }, 1000);
한줄로 만들어 주세여~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addTextEventListener.js
> +    });
한줄로 만들어 주세여~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addTextEventListener.js
> +  });
한줄로 만들어 주세여~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +    }, 2000);
한줄로 만들어 주세여~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +    }, 2000);
한줄로 만들어 주세여~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +      }, 1000);
한줄로 만들어 주세여~~

2022-02-02 09:12 UTC, yongjulejule commented on public/javascripts/eventForm/utils/addTimeEventListener.js
> +      }, 1000);
한줄로 만들어 주세여~~

2022-02-02 09:17 UTC, 42ghan commented on public/javascripts/eventForm/utils/addCategoryEventListener.js
> +    }, 2000);
이건 신경 안쓰셔도 됩니다!

2022-02-02 09:47 UTC, jis-kim commented on public/javascripts/utils/eventForm/countByte.js
> +  return bytesCount;
이거 아마 린터 때문 아닐까요?

2022-02-02 09:48 UTC, jis-kim submitted a review, later dismissed
번거로우셨을텐데 감사합니다! 수고하셨어요

2022-02-02 11:56 UTC, yongjulejule approved these changes
고생하셨습니다~~

2022-02-02 12:01 UTC, 42ghan approved these changes
대박 수고하셨습니다!!

2022-02-02 12:23 UTC, jis-kim approved these changes
고생하셨어요~

2022-02-02 12:23 UTC, merged