✨ 이벤트 홍보글 생성 기능
innovationacademy-kr/our42vent pull request #147
Opened 2022-02-01 12:58 UTC by jis-kim

## 개요
- 이벤트 정보 기반으로 복사가 가능한 홍보글을 생성합니다.
## 작업 사항
- 이벤트 생성 후 이벤트 홍보글 생성
- 이벤트 상세보기에서도 공유 버튼으로 홍보글 생성
- 홍보글 내부에서 생성된 링크로 연결되면 쿠키를 이용하여 이벤트 상세 정보 표시
## 변경점
- layouts/desktop-layout 을 layout으로 변경
- 42 access token redis 만료기간 변경
## 스크린샷 (optional)
<img width="661" alt="Screen Shot 2022-02-01 at 9 46 17 PM" src="https://user-images.githubusercontent.com/71019735/151970829-46a0f0f9-ee73-46da-a1f8-61c0249e4c01.png">

close #122
close #133

2022-02-02 01:38 UTC, yongjulejule requested changes
고생하셨습니다~~ 몇 가지만 수정해주세요~~

2022-02-02 01:38 UTC, yongjulejule commented on public/javascripts/eventPromotion/promotionDisplay.js
> +});
파일명은 promotionDisplay인데 하는건 닫는거네요...? 
`clickExitButton`이나.. `clickPromotionExit`... 암튼 다른걸로 바꿔주세요

2022-02-02 01:38 UTC, yongjulejule commented on public/stylesheets/components/popups/event_details_mobile.css
> +  user-select: none;
이 두 아이 순서 바꿔주세요

2022-02-02 01:38 UTC, yongjulejule commented on public/stylesheets/components/popups/event_details_mobile.css
> +  font-size: 19px;
cursor랑 padding 사이로 옮겨주세요

2022-02-02 13:36 UTC, yongjulejule approved these changes
고생하셨습니다~~

2022-02-02 13:37 UTC, 42ghan requested changes
깔끔하게 잘 짜셨네요! 조금만 수정 부탁드립니다 : ]

2022-02-02 13:37 UTC, 42ghan commented on views/components/eventPromotion.ejs
> +          <i class="promotion-copy-button material-icons"> content_copy </i>
- ln 4 & ln 7 각 text 앞 뒤 space 없애주세요

2022-02-02 13:37 UTC, 42ghan commented on public/stylesheets/components/popups/event_details_mobile.css
> +}
- `.details-exit-button, .details-share-button.material-icons` 겹치는 property 들은 같이 선언해주고 각자 적용되는 property 들 따로 선언해주면 어떨까요? 그냥 제안입니다 ㅎㅎ

2022-02-02 13:37 UTC, 42ghan commented on public/stylesheets/components/popups/event_details.css
> +}
- 여기도 겹치면 같이 선언해주는 건 어떨까요?

2022-02-02 13:37 UTC, 42ghan commented on public/javascripts/eventPromotion/generatePromotion.js
> +  textarea.style.height = `${textarea.scrollHeight}px`;
- 1px 넣어줬다가 바로 바꾸는 이유가 있을까요?

2022-02-02 13:37 UTC, 42ghan commented on public/javascripts/eventPromotion/generatePromotion.js
> +    ` ~ ${endAt.replace('T', ' ').substring(0, 16)}\n장소: ${location}`;
- time 포맷 이벤트 상세정보 팝업과 동일하게 하면 어떨까요? 같은 날 있는 이벤트면 날짜 부분이 반복 될 필요 없을 것 같고, 요일 정보도 꼭 나오면 좋을 것 같아서요. 세희님이 만드신 함수 (setRange.js) 가져다 쓰셔도 좋을 것 같습니다.
![Screen Shot 2022-02-02 at 10 19 57 PM](https://user-images.githubusercontent.com/83805691/152161971-012ab97b-66f9-4b34-bf18-e4f43d2a1d47.png)

2022-02-02 13:42 UTC, jis-kim commented on public/javascripts/eventPromotion/generatePromotion.js
> +  textarea.style.height = `${textarea.scrollHeight}px`;
같은 팝업창을 사용하기 때문에 늘어났던 Textarea 크기를 다시 줄여서 line을 셉니다! 저 줄이 없으면 이전에 생성된 크기보다 더 작은 크기로 생성해야 할 때 적용이 안됩니다

2022-02-02 13:44 UTC, jis-kim commented on public/stylesheets/components/popups/event_details.css
> +}
여기 다시보니 알파벳 순도 안맞네요.....

2022-02-02 14:58 UTC, jis-kim commented on public/stylesheets/components/popups/event_details.css
> +}
반영 완료~

2022-02-02 15:05 UTC, 42ghan commented on public/javascripts/eventPromotion/generatePromotion.js
> +  textarea.style.height = `${textarea.scrollHeight}px`;
아하!

2022-02-02 15:07 UTC, 42ghan requested changes

2022-02-02 15:07 UTC, 42ghan commented on public/stylesheets/components/popups/event_details_mobile.css
> +  position: absolute;
absolute 반복됩니다.

2022-02-02 15:10 UTC, 42ghan submitted a review, later dismissed
편안~ 수고하셨습니다~~

2022-02-02 16:30 UTC, sehhong3317 commented on views/components/eventDetails.ejs
>      <div class="category-exit">
요거 하위 div들이 category, share, exit 세개니까 클래스이름을 category-exit 대신 category-share-exit이 어떨까... 소소한 제안해봅니당..

2022-02-02 17:11 UTC, sehhong3317 commented on public/javascripts/eventPromotion/generatePromotion.js
> +  textarea.style.height = `${textarea.scrollHeight}px`;
신기하네요...

2022-02-02 23:49 UTC, sehhong3317 commented on views/components/eventPromotion.ejs
> +  <div class="promotion" autocomplete="off">
홍보글에서는 user가 input을 넣을 일이 없지않나요? autocomplete=off가 왜 필요한지 궁금합니다!

2022-02-03 00:23 UTC, sehhong3317 commented on views/components/eventDetails.ejs
>      <div class="category-exit">
아니면 category-buttons...?

2022-02-03 03:27 UTC, sehhong3317 approved these changes
와 신기해염! 홍보글 생성하는 아이디어 너무 참신합니다. 신기방기!! 수고하셨어요!

2022-02-03 03:30 UTC, yongjulejule requested changes
말씀드린거 수정해주세여

2022-02-03 03:39 UTC, jis-kim commented on views/components/eventDetails.ejs
>      <div class="category-exit">
굿의견~~ 고맙습니다

2022-02-03 03:46 UTC, 42ghan approved these changes
수고하셨습니다!

2022-02-03 03:47 UTC, yongjulejule approved these changes
굿굿~~~

2022-02-03 03:48 UTC, sehhong3317 approved these changes
수고하셨습니다:)

2022-02-03 03:48 UTC, merged