Feature/update intra event fix
innovationacademy-kr/our42vent pull request #163
Opened 2022-02-05 07:15 UTC by jis-kim

## 개요
- update event 제대로 안되던 문제 해결 close #149 
- 42cursus 이벤트만 받아오는 기능 close #160 
- /event/info 에서 my event 안되던 문제 해결 close #162
## 작업 사항
- intra event을 42cursus(21)만 받아오게 변경
- event table의 intraId 타입 변경 (int -> varchar(10))
- intraId 저장 형식을 prefix가 붙는 형태로 변경
## 변경점
- ft_access_token 저장시간을 7200초로 변경
- url이 너무 길어져 axios query string을 params로 분리
- initEventData data수 증가 (exam은 중복문제로 실질적 감소)

[해당 노션 페이지의 Not authorized 에러 처리 참고](https://teal-grill-819.notion.site/42Seoul-intra-fbc25a91167e4bde848958bfb29b1e89)

2022-02-05 08:57 UTC, yongjulejule commented on db/getIntraEvents/getUpdatedEvents.js
> +      return data;
요기 한줄로 만들어도 되지 않나여?

2022-02-05 09:44 UTC, jis-kim commented on db/getIntraEvents/getUpdatedEvents.js
> +      return data;
return이랑 await를 같이 쓰면 린터에서 걸립니다..

2022-02-05 09:44 UTC, yongjulejule commented on db/getIntraEvents/getUpdatedEvents.js
> +      return data;
하하 답변 감사합니다,,,

2022-02-05 09:49 UTC, yongjulejule submitted a review, later dismissed
고생하셨습니다~~~~

2022-02-05 10:56 UTC, 42ghan requested changes
수고하셨습니다! 조금만 수정부탁드립니다.

2022-02-05 10:56 UTC, 42ghan commented on db/getIntraEvents/getEvents.js
> +    const thirdExamList = await getIntraExam(3);
- 이런식으로 쓰는 건 어떨까요? 제안입니다.
```
    const [eventList, secondEventList, examList, secondExamList, thirdExamList] = [
      await getIntraEvent(1),
      await getIntraEvent(2),
      await getIntraExam(1),
      await getIntraExam(2),
      await getIntraExam(3),
    ];
```

2022-02-05 10:56 UTC, 42ghan commented on db/getIntraEvents/getEvents.js
>        return;
- return 하면 finally 못 들어가서 `redisClient.quit()` 이 실행되지 않는 것 같습니다.
- node 에서 실행하는 것이기 때문에 `new Date()` 로그로 찍을 때 timezone 보정해주세요.

2022-02-05 10:56 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
>        return;
여기도 마찬가지인 것 같습니다.

2022-02-05 10:56 UTC, 42ghan commented on db/getIntraEvents/getUpdatedEvents.js
>        return;
아래 `new Date()` 도 timezone 보정 부탁드립니다.

2022-02-05 11:05 UTC, jis-kim commented on db/getIntraEvents/getEvents.js
>        return;
return 해도 finally블록에 도달하므로 quit()실행은 정상적으로 되는 상태입니다.

2022-02-05 16:50 UTC, jis-kim commented on db/getIntraEvents/getUpdatedEvents.js
>        return;
new Date()는 로거에 날짜가 찍히는 관계로 모두 삭제하겠습니다~!

2022-02-06 09:25 UTC, 42ghan approved these changes
수고하셨습니다!

2022-02-06 10:28 UTC, yongjulejule approved these changes
고생하셨습니다~~~~

2022-02-06 12:51 UTC, sehhong3317 approved these changes
노션 참고해서 리뷰했습니당 ;) 재귀쓰신 부분 신기하네요;0 수고하셨습니다!

2022-02-06 12:52 UTC, merged