✨  Sentry 로거 추가 및 에러 핸들링
innovationacademy-kr/our42vent pull request #164
Opened 2022-02-06 13:45 UTC by yongjulejule

## 개요
- Sentry 로거를 추가했습니다.
- winston logs 디렉토리 수정했습니다.
- 전체적인 에러 핸들링을 했습니다.

센트리 링크 : https://sentry.io/organizations/our42vent/
저희 구글 계정으로 접속하시면 됩니당

## 작업 사항
전체적인 에러 핸들링을 수정하였고, sentry 가 작동하도록 설정했습니다.

[에러 핸들링](https://teal-grill-819.notion.site/Error-handling-7d79f7f75b36400c9116b8e323c8005b) ,[센트리](https://teal-grill-819.notion.site/Logging-4bbbf1105834493aa65ca92569953288) 노션 페이지 입니다. 
에러 핸들링 노션에 어떻게 핸들링 했는지 써놓았습니다.

노션 페이지들을 읽어보시고 코드를 보시는게 정신건강에 이롭습니다.

## 변경점
- 이벤트 등록할때 모달창이 뜹니다.
- axios interceptor를 활용한 api를 axios 대신 사용하시면 됩니다.
- .env 에 SENTRY_DSN을 추가 해주세요
- winston 로거 폴더 경로를 수정했습니다.

## 스크린샷 (optional)

2022-02-08 07:32 UTC, yongjulejule commented
에러 페이지 만들어서 연결해주었고, 적당한 메시지를 넣어줬습니다.
<img width="1792" alt="Screen Shot 2022-02-08 at 4 30 37 PM" src="https://user-images.githubusercontent.com/79127797/152938962-ac1970df-2c7e-4d3f-b4ee-4efcc76ac60e.png">

또한 helmet 모듈을 활용하여 헤더를 설정해줬습니다. #169
[노션](https://teal-grill-819.notion.site/Helmet-ab1d038c9bac4cd09dc8ade9c21fc664) 에 아주아주 간략히 정리했습니다..만 자세한 내용을 쓰기에는 공부가 부족하네요ㅕ

2022-02-08 18:01 UTC, 42ghan commented on app.js
>  });
- middleware 디렉토리에 `errorHandler` 미들웨어 함수로 콜백 빼주고, app.js 에서 import 해서 넣어주면 좋을 것 같습니다.

2022-02-08 18:10 UTC, 42ghan commented on public/javascripts/eventDetail/clickEventDetails.js
> +  const data = await api.get(`/event/${eventId}`).catch(err => {
- 원래하던 것처럼 destructure 안해줘도 되나요...?

2022-02-08 18:14 UTC, 42ghan commented on public/javascripts/eventForm/clickNewEventButton.js
> +              generatePromotion(res);
- res 에 기존의 res.data 가 들어가는 건가요..?

2022-02-08 23:12 UTC, yongjulejule commented on public/javascripts/utils/createAxiosInterceptor.js
> +  }
ECONNABORTED가 원래 리퀘스트에러로 뜨는건데, 구글링을 더 해보니까 인터셉터에선 또 달라지는것 같네여,,, 확인해보고 고쳐두겠습니다~~

2022-02-08 23:14 UTC, yongjulejule commented on app.js
> +);
Sentry는 option 객체가 app을 포함하고 있어서 잘 될진 모르겠네여
helmet은 고민했던 부분인데 빼놓겠습니다

2022-02-08 23:16 UTC, yongjulejule commented on public/javascripts/eventDetail/clickEventDetails.js
> +  const data = await api.get(`/event/${eventId}`).catch(err => {
저희가 response의 값을 쓰는게 다 data라서, 인터셉터에서 data만 빼서 옵니다~~

2022-02-08 23:17 UTC, yongjulejule commented on public/javascripts/eventForm/clickNewEventButton.js
> +              generatePromotion(res);
여기는 변수명을 바꿔버릴까 고민하긴 했는데, 일단 말씀하신대로 동작합니당

2022-02-08 23:20 UTC, yongjulejule commented on public/javascripts/utils/createAxiosInterceptor.js
> +  response => response.data,
@42ghan response의 data만 가져오는 곳입니다

2022-02-09 02:29 UTC, 42ghan requested changes
import 순서 한줄만 고쳐주세요 감사합니다

2022-02-09 02:29 UTC, 42ghan commented on public/javascripts/eventList/generateEventList.js
>  import { getFullDate, getFullTime } from './parseDate.js';
제일 위로 가야할 것 같네요

2022-02-09 05:42 UTC, jis-kim requested changes
정 말 수고하셨습니다~

2022-02-09 06:09 UTC, sehhong3317 approved these changes
엄청나게 꼼꼼한 에러 핸들링....감동입니다... 수고하셨습니다!

2022-02-09 08:24 UTC, 42ghan approved these changes
정말 수고하셨습니다! 줄레 짱!

2022-02-09 08:27 UTC, jis-kim approved these changes
수고수고하셨습니다

2022-02-09 08:27 UTC, merged