:sparkles: feat: jwt를 이용한 로그인과 connection pool 모듈화
innovationacademy-kr/our42vent pull request #40
Opened 2022-01-08 14:54 UTC by jis-kim

## 개요
Json Web Token을 사용하여 login 시 access token 발급받는 로직 구현.

## 작업 사항
- app.js에서 const로 쓰이던 pool을 import하는 방식으로 변경
- `config/createPool.js` import로 pool을 사용가능 함.
- jwt를 cookie에 저장하여 `middlewares/userVerify.js`의 `verifyUser`로 토큰 체크.
- /login/42/return success redirection을 /user/insert로 변경후 성공 시 `/`, 실패 시 `/login`으로 redirect.
- token access시엔 `.env`의 `SECRET_KEY`가 필요하므로 연락 바랍니다.

2022-01-08 14:59 UTC, yongjulejule submitted a review, later dismissed
우와 고생하셨습니다~~~

2022-01-08 15:40 UTC, 42ghan requested changes
대박 수고하셨습니다! 리뷰 내용 반영 부탁드립니다 ㅎ

2022-01-08 15:40 UTC, 42ghan commented on app.js
> -app.use('/', ensureLoggedIn('/login'), indexRoute(express, pool));
- ensureLoggedIn은 jwt 토큰 사용하면 못 쓰게 되나요?

2022-01-08 15:40 UTC, 42ghan commented on jwt/jwt_utils.js
> +  };
한 줄로 만들어주세요

2022-01-08 15:40 UTC, 42ghan commented on jwt/jwt_utils.js
> +  });
여기도 한 줄로 만들어주세요

2022-01-08 15:40 UTC, 42ghan commented on jwt/jwt_utils.js
> +      ok: true,
- key 명... ok 말고 다른 거 쓰면 안되나요?? ㅋㅋㅋㅋ 예를 들어 verified 라든지 ^_^

2022-01-08 15:40 UTC, 42ghan commented on middlewares/userVerify.js
> +    res.status(401).json({ error: 'token expired' });
디테일 좋네요 :)

2022-01-08 15:40 UTC, 42ghan commented on controllers/initializePassport.js
>    passport.deserializeUser((obj, cb) => {
- serialize & deserialize 는 없애도 되지 않나요?

2022-01-08 15:40 UTC, 42ghan commented on jwt/jwt_utils.js
> +const accessSign = userId => {
- 특별한 이유가 없다면 style guide 따라서 함수선언으로 처리해주세요. (https://github.com/tipjs/javascript-style-guide#7.1)

2022-01-08 15:40 UTC, 42ghan commented on jwt/jwt_utils.js
> +const accessVerity = token => {
- 특별한 이유가 없다면 style guide 따라서 함수선언으로 처리해주세요. (https://github.com/tipjs/javascript-style-guide#7.1)

2022-01-08 15:40 UTC, 42ghan commented on middlewares/userVerify.js
> +      console.log(result);
줄레님이 만드신 consoleLogger로 change~

2022-01-08 15:40 UTC, 42ghan commented on middlewares/userVerify.js
> +const verifyUser = async (req, res, next) => {
- 특별한 이유가 없다면 style guide 따라서 함수선언으로 처리해주세요. (https://github.com/tipjs/javascript-style-guide#7.1)

2022-01-08 15:40 UTC, 42ghan commented on models/insertNewUser.js
> +      next();
middleware 가 아닌데도 `next()` 가 되나요??

2022-01-08 15:40 UTC, 42ghan commented on models/selectUser.js
> +  return rows[0];
- array 로 받는 이유가 있나요??

2022-01-08 15:40 UTC, 42ghan commented on routes/index.js
> +  router.get('/', verifyUser, (req, res) => indexController(req, res));
- 이전에는 `pool` 을 넘겨줘야해서 `(req, res) => indexController(req, res, pool)` 이렇게 작성했는데 이제  `indexController` 를 middleware 로 쓸 수 있지 않을까요..? (제가 잘 못 아는 걸 수도)

2022-01-08 15:40 UTC, 42ghan commented on routes/user.js
> +  return router;
- `router/index.js` 에서와 마찬가지로 `(res, req) => loginController(res, req)` 를 `loginController` 로 대체 가능하지 않나요? (제가 잘못 아는 걸 수도 ㅎㅎ)

2022-01-08 15:43 UTC, 42ghan commented on routes/user.js
> +  return router;
- 방금 테스트 해봤는데 되는 것 같아요. 인자 자동으로 (res, req) 넘겨주니까 인자 생략하고 함수명만 적어주면 될 것 같습니다.
![Screen Shot 2022-01-09 at 12 42 49 AM](https://user-images.githubusercontent.com/83805691/148650483-d6db37cb-25f9-466a-a9e5-bca880f0531b.png)

2022-01-08 16:04 UTC, jis-kim commented on models/insertNewUser.js
> +      next();
insertNewUser에 next로 익명 함수를 넘겨주고 그걸 실행합니다! 지금 생각해보니 굳이 싶긴 하네요....

2022-01-08 16:08 UTC, jis-kim commented on models/selectUser.js
> +  return rows[0];
원래 [rows, fields]로 형태로 받는데 field를 생략한 형태입니다. 지금 테스트 해보니 array 표시를 안해주면 rows뿐만 아니라 field도 받아오네요.

2022-01-08 16:09 UTC, jis-kim commented on routes/index.js
> +  router.get('/', verifyUser, (req, res) => indexController(req, res));
밑 사항과 같이 반영해서 push 하겠습니다~!

2022-01-08 16:10 UTC, jis-kim commented on jwt/jwt_utils.js
> +      ok: true,
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ verified로 수정하겠습니다..

2022-01-08 16:10 UTC, yongjulejule commented on models/selectUser.js
> +  return rows[0];
이거 [{rows}] 일케는 접근 안되나여? ㅎㅎ

2022-01-08 16:14 UTC, jis-kim commented on controllers/initializePassport.js
>    passport.deserializeUser((obj, cb) => {
안하면 에러가 납니다 아마 42 auth 처리를 저걸로 하는 것 같네요

2022-01-08 16:16 UTC, jis-kim commented on models/selectUser.js
> +  return rows[0];
굳이?^^

2022-01-08 16:17 UTC, yongjulejule commented on models/selectUser.js
> +  return rows[0];
:sosadjule:

2022-01-08 16:18 UTC, 42ghan commented on models/selectUser.js
> +  return rows[0];
아하 좋습니다!

2022-01-08 16:18 UTC, 42ghan commented on controllers/initializePassport.js
>    passport.deserializeUser((obj, cb) => {
확인 감사해요~

2022-01-09 00:18 UTC, yongjulejule approved these changes
부지런지수~~~

2022-01-09 01:09 UTC, 42ghan approved these changes
정말 수고많으셨습니다!

2022-01-09 01:09 UTC, 42ghan commented on controllers/loginController.js
> +      res.cookie('accessToken', accessToken, { httpOnly: true });
- 그냥 질문, cookie 도 expiration time 설정 해줘야하지 않나요?
- 추후 cookie attribute들 찾아보시고 보안에 필요한 부분들 추가해주시면 좋을 것 같습니다.

2022-01-09 01:37 UTC, sehhong3317 approved these changes

2022-01-09 01:37 UTC, merged

2022-01-09 01:40 UTC, jis-kim commented
@42ghan 리뷰에 답코멘트를....어떻게달죠..?ㅋㅋㅋㅋㅋ 암튼 몰라서 댓글로 남깁니다.. 깃모지보단 type에 따라 커밋 메세지를 작성했는데 refactoring 까진 아니고 단순 스타일 변화라고 생각해서 style로 사용했습니다 .  💄 이 ui 수정에만 해당된다면 커밋 메세지를 나누거나 깃모지를 바꿀 필요가 있을 것 같네요🤔