✨ refresh token을 이용한 유저 검중 추가
innovationacademy-kr/our42vent pull request #53
Opened 2022-01-12 11:00 UTC by yongjulejule

## 개요
- refresh token을 이용한 유저 검증 기능을 추가
- refresh token을 저장하기 위한 DB 쿼리문 추가
- 로그아웃 기능 구현
## 작업 사항
refresh token을 기반으로 access token을 재발급 받는 미들웨어를 추가하였습니다.
 
로그인시 accesstoken과 refreshtoken이 같이 발급되며 accesstoken이 만료되고 refreshtoken이 남아있으면
accesstoken이 재발급 되어 유저가 여전히 로그인 상태를 유지하는 방식입니다. 
<img width="818" alt="Screen Shot 2022-01-12 at 7 56 37 PM" src="https://user-images.githubusercontent.com/79127797/149127518-fc836d4f-2bb9-4f31-8b6b-ae385189c38a.png">

refreshToken이 db에 저장되어야 해서 테이블을 만들었고, 
sql 내부에 이벤트를 생성하여 만료되면 자동으로 토큰을 삭제하는 쿼리문을 만들었습니다.

```shell
cd ./db/init
bash init_sql.sh
```
와 같이 실행하면 추가한 DB 테이블과 이벤트가 생성되며 
만약 이벤트 생성에서 에러가 난다면 권한이 없는 것이니 권한 있는 계정으로 mysql에 접속해서 쿼리문을 직접 입력해주시면 됩니다!!

## 스크린샷 (optional)

2022-01-12 11:03 UTC, jis-kim commented on models/accessTokenDB.js
> +import consoleLogger from '../lib/consoleLogger.js';
token db에 접근하는 파일입니다. 기존 insertNewToken / selectToken으로 나눠져있던 파일을 합쳤습니다.
insertNewToken에서 New도 제외하였습니다.

2022-01-12 11:04 UTC, jis-kim commented on models/accessUserDB.js
> +import consoleLogger from '../lib/consoleLogger.js';
user db에 접근하는 파일입니다. accessTokenDB 파일을 합친 방식과 거의 같습니다.

2022-01-12 11:04 UTC, jis-kim commented on middlewares/verifyUser.js
> +export async function verifyUser(req, res, next) {
인증 미들웨어로 거의 모든 페이지 라우팅 시에 사용해주시면 됩니다.

2022-01-12 12:55 UTC, 42ghan approved these changes
수고 많으셨습니다!

2022-01-12 12:55 UTC, 42ghan commented on controllers/initializePassport.js
> +          consoleLogger.info(user);
- 로그 발생 위치 알 수 있게 앞에 로그 내용 + : 더해주시면 좋을 것 같아요.

2022-01-12 12:55 UTC, 42ghan commented on controllers/loginController.js
> +import { insertToken } from '../models/accessTokenDB.js';
- ...qrsTUv... 순서 맞춰주세요 :)

2022-01-12 12:55 UTC, 42ghan commented on controllers/initializePassport.js
>  const profileToUser = async (token, rt, profile) => {
- 특별한 이유가 없다면 style guide 따라서 함수선언으로 처리해주세요. (https://github.com/tipjs/javascript-style-guide#7.1)

2022-01-12 12:55 UTC, 42ghan commented on controllers/loginController.js
> +      });
- 추후에 서버에서 돌릴 때 `Secure` 쿠키 attribute 도 추가하면 좋을 것 같은데 // TODO: 로 highlight 부탁드립니다.

2022-01-12 12:55 UTC, 42ghan commented on db/init/create_table_event.sql
> +CREATE TABLE if not exists event (
- if not exists 대문자로 써주세요.

2022-01-12 12:55 UTC, 42ghan commented on db/init/create_table_my_event.sql
> +CREATE TABLE if not exists my_event (
- if not exists 대문자로 써주세요.

2022-01-12 12:55 UTC, 42ghan commented on controllers/logoutController.js
> +import consoleLogger from '../lib/consoleLogger.js';
- ..jkLMno.. 순서 맞춰주세요.

2022-01-12 12:55 UTC, 42ghan commented on controllers/loginController.js
> +function loginController(req, res) {
- ln36 지우고 함수 정의할 때 export default 해주세요.

2022-01-12 12:55 UTC, 42ghan commented on controllers/logoutController.js
> +async function logoutController(req, res, next) {
- ln20 지우고 함수 정의할 때 export default 해주세요.

2022-01-12 12:55 UTC, 42ghan commented on db/init/create_table_token.sql
> +create table if not exists token(
if not exists 대문자로 써주세요.

2022-01-12 12:55 UTC, 42ghan commented on db/init/create_table_user.sql
> +CREATE TABLE if not exists user (
- if not exists 대문자로 써주세요.

2022-01-12 12:55 UTC, 42ghan commented on db/init/set_token_event.sql
> +do DELETE FROM token where expireAt <= CURRENT_TIMESTAMP
- 대문자로...

2022-01-12 12:55 UTC, 42ghan commented on db/init/start_event.sql
> +SET global event_scheduler = on
- global & on 대문자로 써주세요.

2022-01-12 12:55 UTC, 42ghan commented on lib/jwtUtils.js
> +  let decoded = null;
- `decoded` 가 let 이어야할 이유가 있나요?

2022-01-12 12:55 UTC, 42ghan commented on lib/jwtUtils.js
> +export { accessSign, accessVerify, refreshSign, refreshVerify };
- 함수 정의에서 export 해주세요.

2022-01-12 12:55 UTC, 42ghan commented on middlewares/verifyUser.js
> +          sameSite: 'lax',
- 여기도 추후에 `Secure` attribute 더하게 // TODO: 주석 써주세요

2022-01-12 12:55 UTC, 42ghan commented on middlewares/verifyUser.js
> +export async function verifyUser(req, res, next) {
- 함수 위에 한줄 요약 설명 comment 달아주시면 좋을 것 같습니다.

2022-01-12 12:55 UTC, 42ghan commented on middlewares/verifyUser.js
> +export async function verifyLoginUser(req, res, next) {
- 함수 위에 한줄 요약 설명 comment 달아주시면 좋을 것 같습니다.

2022-01-12 12:55 UTC, 42ghan commented on middlewares/verifyUser.js
> +          sameSite: 'lax',
- 여기도 추후에 Secure attribute 더하게 // TODO: 주석 써주세요.

2022-01-12 12:55 UTC, 42ghan commented on middlewares/verifyUser.js
> +          expires: new Date(Date.now() + 1000 * 60 * 60),
- 통일성을 위해 1000 * 60 * 60 말고 ...e... 포맷으로 쓰고 주석 달아주세요.

2022-01-12 12:55 UTC, 42ghan commented on models/accessTokenDB.js
> +import pool from '../config/createPool.js';
- import 순서 맞춰주세요.

2022-01-12 12:55 UTC, 42ghan commented on models/accessTokenDB.js
> +    const [rows] = await pool.query(sql, [id]);
- execute 대신 query 사용하는 이유가 있나요?

2022-01-12 12:55 UTC, 42ghan commented on models/accessTokenDB.js
> +import consoleLogger from '../lib/consoleLogger.js';
- 파일명 accessTokenTable.js 로 수정 요청드립니다.

2022-01-12 12:55 UTC, 42ghan commented on models/accessUserDB.js
> +import consoleLogger from '../lib/consoleLogger.js';
- 파일명 accessUserTable.js 로 수정 요청드립니다.

2022-01-12 12:55 UTC, 42ghan commented on models/accessUserDB.js
> +import pool from '../config/createPool.js';
- import 순서 맞춰주세요.

2022-01-12 12:55 UTC, 42ghan commented on models/accessUserDB.js
> +    const [rows] = await pool.query(sql, [id]);
- 여기도 execute 대신 query 사용하는 이유가 있나요?

2022-01-12 12:55 UTC, 42ghan commented on models/accessUserDB.js
> +      consoleLogger.info('rows: ', rows);
- logger 유지 한다면 어디서 발생하는지 알 수 있게 앞에 설명 + : 붙여주세요.

2022-01-12 12:55 UTC, 42ghan commented on models/accessUserDB.js
> +        consoleLogger.error(`query error : ${err}`);
- 어디서 발생하는지 에러인지 알 수 있게 앞에 설명 + : 붙여주세요.

2022-01-12 12:55 UTC, 42ghan commented on models/insertEvent.js
>  import pool from '../config/createPool.js';
- 여기도 import 순서 맞춰주세요.

2022-01-12 12:57 UTC, 42ghan requested changes
실수로 approve 했네요 ㅎㅎ

2022-01-12 13:05 UTC, jis-kim commented on models/accessUserDB.js
> +    const [rows] = await pool.query(sql, [id]);
값을 저렇게 배열로 받아오는 방식을 쓰려면 query를 사용해야 합니다.
execute하면 then에서 리턴을 해서...어떻게..해야 하는데 그게 잘 안돼서 query로 대체하였습니다... :sosadjule:

2022-01-12 13:15 UTC, yongjulejule commented on controllers/loginController.js
> +      });
이거 지금 그냥 설정 해둘께요

2022-01-12 13:17 UTC, 42ghan commented on models/accessUserDB.js
> +    const [rows] = await pool.query(sql, [id]);
- 저는 결과가 똑같이 나오는 것 같은데 한번만 더 확인 부탁드립니다.

2022-01-12 13:31 UTC, yongjulejule commented on lib/jwtUtils.js
> +  let decoded = null;
있었는데 없어졌습니다... 고쳐놓을께요

2022-01-12 13:32 UTC, jis-kim commented on models/accessUserDB.js
> +    const [rows] = await pool.query(sql, [id]);
- 프로미스 마스터에게 따봉 드립니다.

2022-01-12 15:17 UTC, 42ghan requested changes
수고하셨지만 한번더 : ]

2022-01-12 15:17 UTC, 42ghan commented on controllers/initializePassport.js
> +export default function iniializePassport(passport) {
- initializePassport 로 되돌려주세요.

2022-01-12 15:17 UTC, 42ghan commented on controllers/initializePassport.js
> +// 42-api의 유저 profile에서 필요한 유저 정보 추출
- 유저 -> 사용자

2022-01-12 15:17 UTC, 42ghan commented on controllers/initializePassport.js
> +          consoleLogger.info('FortyTwoStrategy : ', user);
- class 명 대신 함수명 들어가게 해주세요.

2022-01-12 15:19 UTC, jis-kim commented on controllers/initializePassport.js
> +export default function iniializePassport(passport) {
이녈라이즈패스포트

2022-01-12 15:51 UTC, jis-kim requested changes
ㅎㅎ 늦게 올려서 죄송합니다

2022-01-12 15:51 UTC, jis-kim commented on db/init/set_token_event.sql
> +do DELETE FROM token WHERE expireAt <= CURRENT_TIMESTAMP
안녕하세요.. 여기 SCHEDULE EVERY 10 MINUTE 
STARTS ... DO 까지 대문자로 변경 부탁드립니다.
MINUTE과 STARTS 사이에 개행도 넣어주세요.

2022-01-12 15:51 UTC, jis-kim commented on models/accessTokenTable.js
> +  const sql = 'DELETE FROM token where userId=?';
여기 where도 대문자로 해주세요..~~~~

2022-01-12 16:19 UTC, 42ghan approved these changes
정말 수고하셨습니다...

2022-01-12 16:21 UTC, jis-kim approved these changes
수고하셨습니다 뿌듯하네요~~!!

2022-01-13 07:54 UTC, sehhong3317 approved these changes
완전 감동!!

2022-01-13 07:54 UTC, merged