✨  내가 생성한 이벤트 페이지 구현
innovationacademy-kr/our42vent pull request #91
Opened 2022-01-22 08:17 UTC by yongjulejule

## 개요
내가 생성한 이벤트 페이지를 구현하였습니다.
## 작업 사항
- 스크롤을 오늘 이후 이벤트에 고정시켰습니다.
- 이벤트 리스너를 활용하여 이벤트 삭제  및 편집 가능을 구현하였습니다.
- sweetalert2 라는 모듈을 이용하여 모달 창을 띄웠습니다.
- sql문에서 where id=? creator=? 조건을 줘서 크리에이터랑 유저 아이디가 매칭되어야 작동하게 바꾸었습니다.
- 홍보글 생성 html button에 submit attribute가 있어서 생기던 버그를 수정하였습니다.
- URL 구조를 회의 내용에 따라 변경하였습니다.
- mixin을 활용하여 sweetAlert 모듈화하였습니다.

## 변경점
- 내가 생성한 이벤트 페이지가 작동합니다.
  - 수정 아이콘을 누르면 이벤트 편집 창이 떠서, 편집이 가능합니다.
  - 삭제 아이콘을 누르면 모달 창이 뜨고, DB에서 삭제가 됩니다.
  - 자세한 내용은 [노션](https://teal-grill-819.notion.site/event-52c0cb01e22f48bca9739b619b0138df)을 참고해주세요
- 모달 창을 띄우는 sweetalert2 모듈을 추가했습니다.
  - `alertModal, confirmModal` 함수를 만들어 모듈화 했습니다.  
  - 자세한 내용은 [노션](https://teal-grill-819.notion.site/SweetAlert-87915a2c70c7454e8b18b9989ea59441)을 참고해주세요

## 스크린샷 (optional)
<img width="1792" alt="Screen Shot 2022-01-22 at 5 16 43 PM" src="https://user-images.githubusercontent.com/79127797/150630659-cd93cd1f-b122-421e-b264-0b1cfde445ec.png">

2022-01-22 12:27 UTC, 42ghan requested changes
수고하셨습니다! 리뷰 반영해서 수정 부탁드립니다 :)

2022-01-22 12:27 UTC, 42ghan commented on public/javascripts/eventList/generateEventList.js
> +      ` ${+eventMonth}월 ${+eventDate}일 ${dayWords[day]}요일, ${eventYear}`
- Number() 를 쓰면 좋을 것 같습니다... 좀더 명시적으로 가죠.

2022-01-22 12:27 UTC, 42ghan commented on public/javascripts/eventList/generateEventList.js
> +    const curDate = getFullDate(new Date(beginYear, +beginMonth - 1, +beginDate + i));
- 여기도 Number() 가 좋습니다.

2022-01-22 12:43 UTC, yongjulejule commented on routes/event.js
> +  router.put('/:eventId', formidable(), eventEditController);
/ -> /:eventId -> /list/* 순서로 바꾸기

2022-01-22 12:43 UTC, jis-kim requested changes
수고하셨습니다. 수정사항 반영 부탁드립니다!

2022-01-22 12:43 UTC, jis-kim commented on public/javascripts/eventList/deleteEventListener.js
> +function deleteEventListener(event) {
deleteEvent() removeEvent중 하나로 수정해주세요! 딜리트는 이벤트가 아니기 때문입니다

2022-01-22 12:43 UTC, jis-kim commented on public/javascripts/eventList/deleteEventListener.js
> +export default function addDeleteEventListener() {
함수명 수정부탁드립니다. addClickListenerForDelete..가 제안되었으나 조금만 더 고민해주세요

2022-01-22 12:43 UTC, jis-kim commented on public/javascripts/eventList/editEventListener.js
> +async function editEventListener(event) {
이것도 함수명 수정 부탁드립니다 사유: edit도 이벤트가 아님.

2022-01-22 12:43 UTC, jis-kim commented on public/javascripts/eventList/editEventListener.js
> +export default function addEditEventListener() {
함수명과 파일명 둘 다 수정 부탁드립니다.

2022-01-22 12:43 UTC, jis-kim commented on public/javascripts/eventList/generateEventList.js
> +      headers: { 'Content-Type': 'application/json' },
불필요한 헤더로 보입니다.

2022-01-22 14:57 UTC, yongjulejule commented on public/javascripts/eventList/deleteEventListener.js
> +export default function addDeleteEventListener() {
10분동안 고민했습니다. 이게 최선입니다 하하

2022-01-23 00:34 UTC, yongjulejule commented
DB접근시 에러는 일단 status 500으로 줬고, 프론트에서 에러나는 경우는 적절히 리다이렉션 시켰는데 어떻게 해야할진 차차 생각해봅시다 ㅎㅎㅎㅎ

2022-01-23 00:38 UTC, yongjulejule commented on routes/event.js
> +  router.put('/:eventId', formidable(), eventEditController);
아니 얘가 순서를 바꾸면 터져요!  정확히는 `get(/:eventId)` 가 `get('/list')` 랑  `get('/list/data')` 보다 위에 오면 터집니다.... 대체 왜?

2022-01-23 02:34 UTC, 42ghan commented on routes/event.js
> +  router.put('/:eventId', formidable(), eventEditController);
옹...list 를 params 로 여기나보네요... 그대로 두죠 ㅋㅋㅋ

2022-01-23 02:42 UTC, 42ghan approved these changes
수고하셨습니다! 몇가지 작은 수정 요청드렸습니다 ㅎㅎ 다음 pr 에 반영해주세요 : ]

2022-01-23 02:42 UTC, 42ghan commented on controllers/eventListController.js
> +import consoleLogger from '../lib/consoleLogger.js';
- ...LMnop... 제일 위로 올라가야합니다... 다음 pr 에 반영해주세요.

2022-01-23 02:42 UTC, 42ghan commented on models/accessEventTable.js
> +// eventId 기반으로 이벤트 삭제
- 다음 pr 에 개행 넣어주세요.

2022-01-23 02:42 UTC, 42ghan commented on models/accessEventTable.js
>  // 이벤트 insert 쿼리
- 여기도 개행...

2022-01-23 03:03 UTC, 42ghan approved these changes
ㅋㅋㅋ 그새 바꾸셨군요 ㅋㅋㅋ 감사합니다 편안하군요 :D

2022-01-23 03:32 UTC, jis-kim commented on routes/event.js
> +  router.put('/:eventId', formidable(), eventEditController);
ghan님 말이 맞는듯..ㅋㅋㅋㅋ 이 얘기도 어디서 본 것 같은데 기억이 안나네요 🤔

2022-01-23 03:37 UTC, 42ghan commented on routes/event.js
> +  router.put('/:eventId', formidable(), eventEditController);
저런 경우 아마 get /:eventId 한 라우터 두고 if (req.params.eventId === list) 이런 식으로 쪼개는 방법이 있을텐데... 굳이싶죠 ㅋㅋㅋㅋ 그냥 원래대로 두는게 좋을 것 같아요!

2022-01-23 04:44 UTC, jis-kim approved these changes
너무 수고 많으셨습니다 코딩줄레~~

2022-01-24 08:37 UTC, sehhong3317 approved these changes
일단 approve해놓고 나중에 개인적으로 질문 생기면 질문할게요!

2022-01-24 08:37 UTC, merged